<a href="https://colab.research.google.com/github/YogeshRajgure/iNeuron_Assignments/blob/main/Assignment7_YogeshRajgure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.**
###**HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.**

In [ ]:
import numpy as np

def dummy_vander(x,n = None, increasing = False):
    
    if n == None:
        n = len(x)
        
    final_mat = list()
    
    
    if increasing == False:
        
        for i in x:
            
            row_mat = []
            for j in range(n-1,-1,-1):
            
                row_mat.append(i**(j))
            
            final_mat.append(row_mat)
        
    else:
        for i in x:
            
            row_mat = []
            for j in range(n):
            
                row_mat.append(i**(j))
            
            final_mat.append(row_mat)
        
    return np.array(final_mat)
    

In [ ]:
x= np.array([1, 2, 3, 5])
n= 3

In [ ]:
dummy_vander(x,n)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [ ]:
# check with real function

np.vander(x,n)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [ ]:
dummy_vander(x,n,increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

In [ ]:
# check with real function

np.vander(x,n, increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

###**Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.**

In [ ]:
def moving_avg(n, k):
    
    x = list()
    x_avg = list()
    
    for i in range(n):
        x.append(int(input())) 
    
    for i in range(len(x)-k+1):
        s = 0
        for j in range(k):
            s += x[i + j]    
        x_avg.append(s // k)
    
    return x_avg

In [ ]:
n=13
k=3
moving_avg(n, k)

3
5
7
2
8
10
11
65
72
81
99
100
150


[5, 4, 5, 6, 9, 28, 49, 72, 84, 93, 116]

In [ ]:
#check with given input and output
moving_avg(10, 4)

10
20
30
40
50
60
70
80
90
100


[25, 35, 45, 55, 65, 75, 85]